spring:
  application:
    name: Quiz
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Quiz;encrypt=true;trustServerCertificate=true
    username: sa
    password: admin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  session:
    store-type: none
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  thymeleaf:
    encoding: UTF-8

server:
  port: 6769
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
